# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI - Unit and Robot Tests

# wokflow is triggered on following
on:
  # trigger on push to main
  push:
    branches: [ main  , MELA2-81 ]
  # trigger on new PR to main
  pull_request:
    branches: [ main]
  # enables manual triggering
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  run-tests: 
    name: Run Unit and Robot Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13.5"]
        r-version: ["4.5.0"]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]

    - name: Run pylint
      run: |
        pylint lukefi --output-format=github

    - name: Run pylint, TODO warnings only
      continue-on-error: true
      run: |
        pylint lukefi --output-format=github --disable=all --enable=fixme --fail-under=0
    
    - name: Run mypy
      run: |
        sudo apt-get install -y jq
        mypy -p lukefi --output=json | jq -r '"::\(.severity) title=Mypy issue,file=\(.file),line=\(.line),col=\(.column)::\(.message)"'

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2

    - name: Compile shared libraries
      run: |
        make -C lukefi/metsi/forestry/c

    - name: Test with pytest
      run: |
        python -m pytest --junit-xml=pytest.xml --cov=lukefi --cov-report xml --cov-branch

    - name: Ensure no stale GHCR creds
      run: |
        docker logout ghcr.io || true

    - name: Check if this run can access private GHCR
      id: ghcr_access
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
          echo "can_pull=false" >> $GITHUB_OUTPUT
          echo "This is a PR from a fork; skipping private GHCR pull."
        else
          echo "can_pull=true" >> $GITHUB_OUTPUT
        fi

    - name: Log in to GHCR
      if: steps.ghcr_access.outputs.can_pull == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Diagnose GHCR access
      if: steps.ghcr_access.outputs.can_pull == 'true'
      run: |
        set -euo pipefail
        TOKEN=$(echo -n "${{ github.token }}")
        # Probe the registry API; expect HTTP 200/401/403
        code=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $TOKEN" \
          https://ghcr.io/v2/lukefi/growth-libs/tags/list)
        echo "GHCR /tags/list status: $code"
        if [ "$code" != "200" ]; then
          echo "Likely missing repo access to the private package, or wrong package path/tag."
          exit 1
        fi

    - name: Pull growth-libs image
      if: steps.ghcr_access.outputs.can_pull == 'true'
      run: |
        set -euxo pipefail
        docker pull ghcr.io/lukefi/growth-libs:linux-x64-test || {
          echo "Pull failed. Printing debug info..."
          docker logout ghcr.io || true
          exit 1
        }

    - name: Extract binaries from image
      if: steps.ghcr_access.outputs.can_pull == 'true'
      env:
        IMAGE: ghcr.io/lukefi/growth-libs:linux-x64-test
        DEST: ${{ github.workspace }}/data/motti
      run: |
        set -euo pipefail
        mkdir -p "$DEST"
        docker run --rm "$IMAGE" sh -lc '
          set -e
          cd /
          files="$(ls -p | grep -v / || true)"
          if [ -n "$files" ]; then
            tar -cf - $files
          else
            tar -cf - --files-from /dev/null
          fi
        ' | tar -C "$DEST" -xf -
        chmod +x "$DEST"/* 2>/dev/null || true
        ls -al "$DEST" || true

    - name: Run Robot Tests
      run: |
        export PYTHONPATH=${GITHUB_WORKSPACE}
        robot --xunit robottest.xml tests/robot

    - name: Upload testing results
      if: (!cancelled())
      uses: actions/upload-artifact@v4
      with:
        name: Test Results (Python ${{ matrix.python-version }}, R ${{ matrix.r-version}})
        path: |
          coverage.xml
          pytest.xml
          log.html
          report.html
          output.xml
          robottest.xml
          tests/robot/**/output/

    - name: Clean up
      run: |
        make -C lukefi/metsi/forestry/c clean
        rm -rf ./data/motti || true

  
  publish-test-results:
    name: "Publish Test Results"
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    if: (!cancelled())

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            artifacts/**/pytest.xml
            artifacts/**/robottest.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: artifacts/**/coverage.xml
          format: markdown
          output: both
          badge: true
          fail_below_min: true
          hide_complexity: true
          hide_branch_rate: false
          indicators: true
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          path: code-coverage-results.md
